export const SET_SHOW_CONVERSATION = "SET_SHOW_CONVERSATION"
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION"
export const GET_CONVERSATION_MESSAGES = "GET_CONVERSATION_MESSAGES"
export const SET_LOADING_MESSAGES = "SET_LOADING_MESSAGES"
export const NEW_MESSAGE = "NEW_MESSAGE";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS"