export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_FRIEND_REQUESTS = "FETCH_FRIEND_REQUESTS";
export const FETCH_FRIENDS = "FETCH_FRIENDS";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";